#切片，取一个list或tuple的部分元素是非常常见的操作
L=['wenjie','boopo','tubuo','bbbp']
#取list的前几个元素
print(L[0],L[1])
print([L[0],L[1]])
r=[]
n=3
for i in range(n):
	r.append(L[i])
print(r)
#切片Slice操作符
print(L[0:3])#从索引0开始取，直到索引3为止，不包括索引3
print(L[:3])#如果是第一个索引，还可以省略
print(L[1:3])#从索引1开始
print(L[-1])#取倒数第一个元素，也支持倒数切片
print(L[-2:])#从倒数第二个开始切片
print(L[-2:-1])#-1是倒数第一个元素的索引,但是不包括倒数第一个
L=list(range(100))
print(L)
print(L[:10])
print(L[-10:])
print(L[:10:2])#前10个数，每两个取一个
print(L[::5])#所有数，每5个取一个
print(L[:])#只写[:]就可以复制一个list
#tuple也是一种list，只不过tuple不可变，tuple也可以切片，只是操作的结果仍然是tuple
print((0,1,2,3,4,5)[:3])
print('ABCDESF'[:3])#字符串也可以当作一种list，也可以进行切片操作
